apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::308346476861:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-5Y6QTJNQ2W89
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::308346476861:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-10-17T14:54:15Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "125871"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 85f5bac1-c0ea-4d7f-bf75-749e4d4074e5
